trigger:
  branches:
    include:
      - main  # fix typo: "mainn" → "main"

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install dependencies and build
  - script: |
      npm install
      npm run build    # adjust for your framework
    displayName: 'Build static files'

  # Upload build output to Azure Blob Storage
  - task: AzureCLI@2
    inputs:
      connectedServiceNameARM: 'AzureConnection'  # ✅ FIXED KEY
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload-batch \
          --account-name fouridstestfrontend \
          -s build \
          -d \$web \
          --auth-mode login
    displayName: 'Deploy to Blob Storage'
