trigger:
  branches:
    include:
      - main   # change if your branch is different

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install dependencies & build
  - script: |
      npm ci
      npm run build
    displayName: 'Build project'

  # Upload build output to Azure Blob Storage
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureConnection'   # Service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload-batch \
          --account-name fouridstestfrontend \
          -s build \
          -d \$web \
          --auth-mode login
    displayName: 'Deploy to Azure Blob Storage'
